### ISSUE TITLE
Implement Key.get decently

### ISSUE THREAD

**Issue by Drup** [mirage/functoria#13]
Currently, if you call it before command line parsing, it's going to alway returns the default values. 

I see two ways to fix it:
- Add a way to check that command line parsing at occurred and raise an exception if it's not the case.
- Introduce a fully abstract datatype needed by `Key.get` and that is only provided inside the configure and connect methods.

One uses exception, one is type-crazy, I'm not sure which one I prefer ...

**Comment by dbuenzli** [comment]
Don't know anything about the context but if this is considered a programming error then just raise `Invalid_argument`: it doesn't seem like a constraint that is tricky to enforce by the client. Using a datatype for that seems like a greater burden for what is a constraint like "you have to call `M.init` before being able to use the module".

**Comment by Drup** [comment]
> "you have to call M.init before being able to use the module".

It's trickier than that. There are multiple phases during configuration and all the methods of a `configurable` are not needed at the same phase. Some before command line parsing, some after. It's clearly possible to get it wrong. Arguably, `Key.get` should not be used to begin with, but it's still a bit used in mirage (I would need to rewrite even more portions of it and I didn't).

@samoth: maybe a solution is to make `connect` and `configure` returns a `Key.value` ....

**Comment by samoht** [comment]
an exception should be enough. Both will cause a compilation error of `config.ml` anyway.

**Comment by samoht** [comment]
>  maybe a solution is to make connect and configure returns a Key.value

if that make the `Key.get` disappear  that might indeed be a good idea.
