### ISSUE TITLE
Key predefined by other keys

### ISSUE THREAD

**Issue by Drup** [mirage/functoria#14]
We could want the ability to add "super keys" that predefine other keys. There are numerous API possibilities, I'm not really sure which one is good, as I don't want to make the current combinators more complicated.

According to @dbuenzli This is a feature that is available in assemblage. This could allow to add back `--xen` and `--unix`.

**Comment by dbuenzli** [comment]
This can be understood by looking at key declaration (`key`) and key value access (`value`) in [this section](http://samoht.github.io/assemblage/Assemblage.Conf.html#1_Configurationkeys). A basic example can be seen where the key [`target_arch`](http://samoht.github.io/assemblage/Assemblage.Conf.html#VALtarget_arch) is set by default to the value of the key [`host_arch`](http://samoht.github.io/assemblage/Assemblage.Conf.html#VALhost_arch) (n.b. the cross-compilation terminology is wrong). Of course the access to a key value can be arbitrarily transformed using the [applicative functor](http://samoht.github.io/assemblage/Assemblage.Conf.html#values).

All this is implemented [here](https://github.com/samoht/assemblage/blob/b980893416dc66ecfa3c489aa3223b370c66fa7a/lib/as_conf.ml).

**Comment by samoht** [comment]
> This could allow to add back --xen and --unix.

That would be great!

**Comment by Drup** [comment]
@dbuenzli There is something I don't understand in the implementation: how do you show the default value of keys in the documentation ? The default value is itself dynamic. In `Assemblage_driver.Conf_spec.ui`, it seems like you don't do it at all.

**Comment by dbuenzli** [comment]
> The default value is itself dynamic.

Yes, that's the reason why defaults value are not shown in man pages (since you may want to actually install those and you don't want them to lie). In general the default value may also be the result of a command line invocation (e.g. `uname -s`). 

The idea at the time was that this would be alleviated by having some form of `show` command in the tool for queries and that programmers defining configuration keys would give a decent description of the dynamics in the doc string of the configuration key.

Given the potential dynamics of a `Conf.app` I'm afraid nothing better can be done, we have a bootstrapping problem here.

It could however be possible to enrich the [`'a value`](https://github.com/samoht/assemblage/blob/b980893416dc66ecfa3c489aa3223b370c66fa7a/lib/as_conf.ml#L40-L44) type to distinguish a value derived from a general `Conf.app`, from the one defined by `Conf.const` or a (currently inexisting) `Conf.cmd`.

**Comment by Drup** [comment]
I don't feel that it's acceptable not to show the default values. Commands are a different problem, because you can perfectly say "the default value is the result of X".

> It could however be possible to enrich the 'a value type to distinguish a value derived from a general Conf.app, from the one defined by Conf.const or a (currently inexisting) Conf.cmd.

Isn't checking that the set of dependency is empty enough ?

**Comment by dbuenzli** [comment]
> I don't feel that it's acceptable not to show the default values. Commands are a different problem, because you can perfectly say "the default value is the result of X".

Well it's the same for configuration values that depend on each other... e.g. for `host-os`, "the default value is the value of `build-os`". And in general it can be more involved than that, e.g. you could imagine the default value of a command line tool being suffixed by `.opt` iff `native-toolchain` is `true`. 

So in general you can't really do something about the problem in the context of cmdliner, except for constant default values. So it's still a good idea to provide a command for exploring a given configuration and its defaults.

> Isn't checking that the set of dependency is empty enough ?

That would indeed do it for `Conf.app`'s of `Conf.const`s.

**Comment by Drup** [comment]
I started thinking about this again. It's relatively easy to implement, however one things bothers me: With the feature describe by @dbuenzli , I can implement key A that depends on key B. I think a more useful feature is the ability to implement key B that will set key A's value.

**Comment by dbuenzli** [comment]
> I can implement key A that depends on key B. I think a more useful feature is the ability to implement key B that will set key A's value. This allows to create keys that influence the value of other predefined keys.

It took me a minute to convince me that this wouldn't end up in being the same. It's a very interesting twist, especially documentation wise. It's certainly less general but it may be perfectly sufficient.

**Comment by Drup** [comment]
> It took me a minute to convince me that this wouldn't end up in being the same.

Yeah, It boils down to the order of definition of the keys. @samoht wanted this feature to be able to have a `--local` or a `--deploy` flag that would set a bunch of other options, some potentially predefined in implementations (like `ip` inside a stack).

The issue is that I'm not sure how to implement that.

**Comment by Drup** [comment]
Regardless of what we choose, all those can't work at runtime (CSP on functions is not going to work the way we do it ...).

**Comment by samoht** [comment]
they don't want at runtime currently so that's fine

**Comment by samoht** [comment]
Is this fixed now? (e.g. with have kind of weird alias, is that enough?)

**Comment by Drup** [comment]
The API is a bit quirky though, but we can probably revisit it when people start using the API (and report that it sucks).
