### ISSUE TITLE
version comparison is inconsistent with opam

### ISSUE THREAD

**Issue by hannesm** [mirage/functoria#149]
while opam's version comparison is inherited from debian, and licensed under LGPL 2.1 (while functoria is ISC licensed), the adhoc version comparison in functoria is incomplete and inconsistent:
- in functoria, a version may only be numbers and `.`
- in opam, `1.0 != 1.0.0`, while in functoria `1.0 = 1.0.0`

this may be an issue in the future, and since I wrote the code last year I wanted to inform others that there may be issues at the end of the road.  I guess the solution [tm] is to develop a version comparison library _from scratch_ with a permissive license, and use this in functoria (and in the best case also in opam).  another solution is to use the opam version comparison (and depend on opam, which would make this library LGPL IIUC).

this is not really urgent - as long as we stick to versions which only contain numbers and `.` (and do not release both `foo.1.0` and `foo.1.0.0`) we're safe.

**Comment by yomimono** [comment]
I think a lot of the logic needed for a standalone library is probably already in https://github.com/avsm/ocaml-version , which looks permissively licensed.

**Comment by hannesm** [comment]
this was my initial hope as well, but ocaml-version only deals with compilers, especially:
```OCaml
let parse s =
  try Scanf.sscanf s "%d.%d.%d+%s" (fun major minor patch extra -> v ~patch ~extra major minor)
  with End_of_file | Scanf.Scan_failure _ -> begin
      try Scanf.sscanf s "%d.%d+%s" (fun major minor extra -> v ~extra major minor)
      with End_of_file | Scanf.Scan_failure _ -> begin
          try Scanf.sscanf s "%d.%d.%d" (fun major minor patch -> v ~patch major minor)
          with End_of_file | Scanf.Scan_failure _ -> begin
              Scanf.sscanf s "%d.%d" (fun major minor -> v major minor)
            end
        end
end
```

will not parse any `3.0~beta5` or `v0.9.0`, or `2017`, or `1.0.0.0.0.0.1` version strings.

**Comment by yomimono** [comment]
In that case, sorry for the noise!
