### ISSUE TITLE
Required keys

### ISSUE THREAD

**Issue by Drup** [mirage/functoria#15]
At the moment, all the keys are optional (and need to have a default value). Apparently, people also want required keys, without a default value.

The good thing is that it should be possible to implement it with barely changing the API, since `default` already has a label.

**Comment by Drup** [comment]
I was thinking about this again: what should be the semantic for required keys available in configure and run stages ?

It seems weird to make it required at `configure` *and* at `runtime`. One solution is to make it optional at configure time. Then, if a value was given at configure time, it's optional at runtime. If no value was given at configure time, then it's required. 
That ways, a value is always specified, but it's a bit complicated.

cc @hannesm since you seem interested for tls things.

**Comment by hannesm** [comment]
For TLS private keys, I would like to have a key required at `runtime` (and for convenience, as you mentioned, if provided at `configure` time, make it optional at `runtime`).  Thus, a unikernel could be configured and built without any private material, and get the keys on startup (`runtime`).

**Comment by Drup** [comment]
Ok, that seems like the good semantics then.

Now, the issue I have is that I'm not sure what `Key.get` should return on required keys that do not have a value yet. Invalid argument seems like a decent option, with the message "always use Key.peek on required keys". 

I could prevent it by typing too ...

**Comment by hannesm** [comment]
I think `invalid_argument` is fine there...

**Comment by samoht** [comment]
This seems an interesting feature with a clear and identified use-case, so could go in before the release if that's not too much trouble to have.
