### ISSUE TITLE
force colors?

### ISSUE THREAD

**Issue by samoht** [mirage/functoria#18]
Seems that there are no color anymore when the mirage tool is called inside a Makefile. I guess the tty auto-dectection does not handle very well that case. 

Maybe add an option to `mirage configure` to force the display or color (using the usual tri-state logics?)

**Comment by Drup** [comment]
@dbuenzli : Do you think the color detection could be improved ?

**Comment by dbuenzli** [comment]
> @dbuenzli : Do you think the color detection could be improved ?

Well I'm basically [doing](https://github.com/dbuenzli/fmt/blob/1f1b34b63c1eab7edb91caf81064a0cb1262c8d1/src/fmt_tty.ml#L34-L40) what everybody is doing (ocaml compiler included). It seems that's it's due to a recent feature of make, see [here](https://gcc.gnu.org/ml/gcc-help/2014-10/msg00053.html). @samoht can you confirm you are using something like make 4+ ? A good way of side-stepping the problem would be to avoid using a broken build system or if you are just using make to run commands, just use a shell-script instead.

**Comment by samoht** [comment]
```
$ make --version
GNU Make 3.81
```
I'm happy to use a more modern build system, once available :-)

**Comment by dbuenzli** [comment]
> GNU Make 3.81

The problem must be elsewhere then: 

```
> cat ./bla.ml 
#!/usr/bin/env ocaml
#use "topfind"
#require "unix"

let isatty = try Unix.(isatty (descr_of_out_channel Pervasives.stdout)) with
| Unix.Unix_error _ -> false

let () = Printf.printf "isatty: %b\n" isatty
> cat Makefile 

all:
	echo $(TERM)
	./bla.ml
> make
echo xterm-256color
xterm-256color
./bla.ml
isatty: true
```

**Comment by samoht** [comment]
Interesting:

```
$ make
echo xterm
xterm
./bla.ml
isatty: false
```

**Comment by dbuenzli** [comment]
Gngngngngngn.

**Comment by dbuenzli** [comment]
(same make version btw. 3.81)

**Comment by samoht** [comment]
This was with iTerm. With Terminal, I get:

```
$ make
echo xterm-256color
xterm-256color
ocaml bla.ml
isatty: false
```

I'll try to test more things..

**Comment by dbuenzli** [comment]
Can you do a `type make`.

**Comment by samoht** [comment]
haha, this is the issue:

```
$ type make
make is aliased to `colourify make'
```

Anyway, Python also fails:
```
$ cat bla.py
import sys
print sys.stdout.isatty()
$ make
echo xterm
xterm
ocaml bla.ml
isatty: false
python bla.py
False
```

so now I need to remember why I've added this alias...

**Comment by dbuenzli** [comment]
Well I don't know what that `colourify` is but I guess it captures stdout and processes it in that case of course `isatty` will be false.

**Comment by samoht** [comment]
ok, that clearly makes sense.

@Drup I still would like to be able to force colors if I want though, as in `opam`:

```
--color=WHEN (absent=auto)
           Colorize the output. WHEN must be one of `always', `never' or
           `auto'.
```

It's clearly not the most critical feature request though :-)

**Comment by dbuenzli** [comment]
This can be plugged into the optional argument of `Fmt_tty.setup_std_outputs`. No environment variable support, yet.
```ocaml
let color =
  let color_enum = ["auto", None; "always", Some `Ansi_tty; "never", Some `None]
  let color_conv = Arg.enum color_enum in 
  let alts = Arg.doc_alts_enum color_enum in 
  let doc = strf "Colorize the output. $(docv) must be %s." alts in
  Arg.(value & opt color_conv None & info ["color"] ~doc ~docv:"WHEN")
```

**Comment by dbuenzli** [comment]
Note, since I already defined this option quite a few times I added an optional `fmt.cli` subpackage to `fmt` that has a term for the option in https://github.com/dbuenzli/fmt/commit/328f1d8deb7deffb9916d9409171c4ad42c96b7c
