### ISSUE TITLE
Change the name of the generated key file

### ISSUE THREAD

**Issue by Drup** [mirage/functoria#21]
`Bootvar` is not used anywhere now. Should I change `Bootvar_gen` ? Into what ?

**Comment by samoht** [comment]
I think this is now fixed. Not sure what was the original issue though...

**Comment by Drup** [comment]
No it's not. The issue is "bootvar" is used nowhere in the documentation but the module generated at runtime is `Bootvar_gen`. 

I think I will rename it `Key_gen`.

**Comment by samoht** [comment]
ok
