### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by samoht** [mirage/functoria#31]
Not sure what is the best way to test functoria, but that would be nice to have some tests in the repo.

**Comment by Drup** [comment]
I kinda consider `mirage-skeleton` my tests ^^'

It doesn't catch some stuff, though, especially breakage on `describe`

**Comment by samoht** [comment]
mirage-skeleton is a good test, but faster tests would be great as well :-)

**Comment by Drup** [comment]
`mirage-skeleton` is much faster if you install all the depext beforehand and add `--no-depext`.

**Comment by samoht** [comment]
in a CI that doesn't make a big difference though :-)

**Comment by Drup** [comment]
Pretty sure it does. opam calling opam depext (calling whatever it calls) takes forever compared to the rest of the process. by bundling a bit call to apt-get before, it would be much faster.

**Comment by Drup** [comment]
"benchmarks":
- `FLAGS=--no-opam make  31,65s user 5,13s system 92% cpu 39,866 total`
- `make  44,73s user 8,80s system 21% cpu 4:14,04 total` in the case where everything is installed.

So, yes, opam depext is slooow.

**Comment by AltGr** [comment]
See my answer at https://github.com/ocaml/opam-depext/issues/31#issuecomment-152680629

**Comment by Drup** [comment]
Example of things to test: https://github.com/mirage/mirage/issues/476

**Comment by yallop** [comment]
We have some [basic tests](https://github.com/yallop/functoria/blob/d468cd696ade2c145a2ca4ad734e5c8e881ddaea/tests/test_functoria_command_line.ml) now.  There's certainly room for more, though.

**Comment by UnixJunkie** [comment]
making opam depext faster would be welcome too

**Comment by samoht** [comment]
Tests have been added so closing.  Please open an issue on `opam-depext` repo if you want to keep track of that improvement request.
