### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by yallop** [mirage/functoria#50]
I'd like to tag the master branch and push a package to opam-repository soon.

@drup, @samoht, others: is there anything that's absolutely essential to fix before I do?

**Comment by Drup** [comment]
Nope, go on!

**Comment by yallop** [comment]
[Tagged](https://github.com/mirage/functoria/tree/1.0.0).  (The `version`'s from the [_oasis file](https://github.com/mirage/functoria/blob/1.0.0/_oasis#L3)).

**Comment by yallop** [comment]
PR: https://github.com/ocaml/opam-repository/pull/5796

**Comment by yallop** [comment]
All done.
