### ISSUE TITLE
"--help" should default to "--help=plain" for non-POSIX unikernels

### ISSUE THREAD

**Issue by mato** [mirage/functoria#61]
Not sure if this is the right place to report this issue: While implementing the `Bootvar` interface for Solo5 I found that the default behaviour of `--help` is `--help=pager` which attempts to call `system()`, which is an abort on a non-POSIX unikernel:

```
$ qemu-system-x86_64  -enable-kvm -nographic -vga none -kernel mir-console.virtio -append "--help"
(...)
STUB: abort: system() called
Aborted
Mirage on Solo5 exiting... Goodbye!
QEMU: Terminated
```

Specifying `--help=plain` produces the correct behaviour (help is displayed as expected). This is likely to confuse future users as the following is displayed if an unknown option is specified:

```
console: unknown option `--foo'.
Usage: console [OPTION]... 
Try `console --help' for more information.
```

Would it be possible to switch the default behaviour to `--help=plain` for non-POSIX unikernels using functoria?

**Comment by samoht** [comment]
Yes that should be possible. I'll have a look at that next week.

**Comment by dbuenzli** [comment]
> Yes that should be possible.

I'm not sure it is. Would [that](https://github.com/dbuenzli/cmdliner/issues/43) be sufficient or you also lack env vars ?

**Comment by mato** [comment]
@dbuenzli `getenv()` is stubbed out to return `NULL` in both Xen (Mini-OS) and Solo5, so as long as the check is "TERM=dumb OR not present" it should be fine.

**Comment by dbuenzli** [comment]
This will be fixed in the next `cmdliner` release. https://github.com/dbuenzli/cmdliner/issues/43#event-942935178

**Comment by hannesm** [comment]
this works nowadays with the new cmdliner (I tested this locally). please reopen if this is still an issue for you.
