### ISSUE TITLE
Provide a way to run commands without escaping issues

### ISSUE THREAD

**Issue by talex5** [mirage/functoria#63]
https://github.com/mirage/mirage-skeleton/pull/147 does:

```
Functoria_app.Cmd.run "rm -f %s/disk.img" dir
```

This is unsafe if `dir` contains spaces or other special characters. Functoria should provide an alternative that doesn't go via the shell.

`Lwt_process` and `Unix.create_process` take arrays instead.
`Bos.Cmd` makes command-lines abstract to acheive the same thing:
https://github.com/dbuenzli/bos/blob/78bd66169f401e6ebf6347cd903cc2f1c3f0b7f8/src/bos.mli#L115

**Comment by samoht** [comment]
+1 to use [Bos](https://github.com/dbuenzli/bos) as much as possible now that it is released :-)

**Comment by hannesm** [comment]
we now use bos, there is no longer any `Functoria_app.Cmd`... bos does it right, you can use it in your own configure and build
