### ISSUE TITLE
it's possible to trigger an ocamlgraph exception

### ISSUE THREAD

**Issue by yomimono** [mirage/functoria#69]
See https://github.com/mirage/mirage-www/pull/486 .  It's not clear to me _why_ this is.  In the linked PR, it's possible to work around the issue by letting a key default to `false` rather than specifying at configuration time that the key's value should be `false` explicitly.

**Comment by Drup** [comment]
I don't really now either (I put a lot of stuff in place to avoid that). It would really help to have a small example to reproduce (`mirage-www` is a bit daunting ....)

**Comment by yomimono** [comment]
https://github.com/yomimono/break-ocamlgraph for a simplified unikernel that still exhibits this behavior.
