### ISSUE TITLE
disable warn_error for a release

### ISSUE THREAD

**Issue by hannesm** [mirage/functoria#78]
I don't think it is a good idea to have warn_error enabled for a release, since these are warnings, and newer OCaml versions can rightfully introduce more warnings (but the release should be flawless) -- in contrast, in a development build the warn_error should be enabled (I'm not sure how to best do this atm... wondering whether topkg has support for this, or maybe some lines in pkg/pkg.ml?)

**Comment by Drup** [comment]
Warn_error is only enabled for warning that have been released, so that's not an issue.

**Comment by hannesm** [comment]
ok then...
