### ISSUE TITLE
ocamlbuild output is badly handled 

### ISSUE THREAD

**Issue by Drup** [mirage/functoria#86]
1. The command to build `config.ml` are printed by default. They shouldn't, when the build works fine, there is no reason to show anything. It's pure noise
2. When the `config.ml` build fail, I get this:
```
Command exited with code 2.
Fatal error: exception (Invalid_argument
   "run ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-tags'\
  \n     'bin_annot,color(always)' '-X' '_build-ukvm' '-pkg' 'mirage'\
  \n     'config.cmxs']: exited with 10")
```
Which is probably the worst way of reporting errors. :)

Ideally, it should only print the ocaml error. 
@hannesm I would solve it myself, but bos is pretty much symbol non-sense for me at this point (and I don't find the API particularly easy to use).

**Comment by dbuenzli** [comment]
The *what* non-sense ?

**Comment by hannesm** [comment]
fixed https://github.com/mirage/functoria/issues/97
